from unittest.mock import AsyncMock, patch

import pytest
from fastapi.testclient import TestClient
from sqlalchemy.orm import Session

from src.aac_app.models.database import BoardSymbol, CommunicationBoard
from src.api.main import app

# Setup TestClient
client = TestClient(app)


@pytest.fixture
def mock_ai_response():
    return [
        {"label": "Apple", "symbol_key": "apple", "color": "#FFCDD2"},
        {"label": "Banana", "symbol_key": "banana", "color": "#FFF9C4"},
    ]


def test_create_board_with_ai(
    test_db_session: Session, setup_test_db, admin_token, admin_user, mock_ai_response
):
    """Test creating a board with AI enabled"""

    # Mock the BoardGenerationService.generate_board_items method
    # Since we instantiate BoardGenerationService inside the route, we need to patch it
    with patch("src.api.routers.boards.BoardGenerationService") as MockServiceClass:
        # Configure the mock instance
        mock_instance = MockServiceClass.return_value
        mock_instance.generate_board_items = AsyncMock(return_value=mock_ai_response)

        # Mock the provider instantiation as well to avoid actual connections
        with patch("src.api.routers.boards.OllamaProvider"):

            response = client.post(
                f"/api/boards/?user_id={admin_user.id}",
                headers={"Authorization": f"Bearer {admin_token}"},
                json={
                    "name": "AI Test Board",
                    "description": "A test board generated by AI",
                    "is_public": False,
                    "ai_enabled": True,
                    "ai_provider": "ollama",
                    "ai_model": "llama3",
                },
            )

            assert response.status_code == 200
            data = response.json()
            assert data["name"] == "AI Test Board"
            assert data["ai_enabled"] is True

            board_id = data["id"]

            # Check if symbols were added to the database
            board = (
                test_db_session.query(CommunicationBoard)
                .filter(CommunicationBoard.id == board_id)
                .first()
            )
            assert board is not None

            # Check symbols
            board_symbols = (
                test_db_session.query(BoardSymbol)
                .filter(BoardSymbol.board_id == board_id)
                .all()
            )
            assert len(board_symbols) == 2

            # Check specific symbol content
            symbol_labels = [bs.custom_text for bs in board_symbols]
            assert "Apple" in symbol_labels
            assert "Banana" in symbol_labels

            # Verify generate_board_items was called
            mock_instance.generate_board_items.assert_called_once()
            args, _ = mock_instance.generate_board_items.call_args
            assert args[0] == "AI Test Board"  # topic/name


def test_create_board_without_ai(
    test_db_session: Session, setup_test_db, admin_token, admin_user
):
    """Test creating a board without AI enabled"""

    response = client.post(
        f"/api/boards/?user_id={admin_user.id}",
        headers={"Authorization": f"Bearer {admin_token}"},
        json={
            "name": "Manual Board",
            "description": "A manually created board",
            "is_public": False,
            "ai_enabled": False,
        },
    )

    assert response.status_code == 200
    data = response.json()
    board_id = data["id"]

    # Check symbols - should be empty
    board_symbols = (
        test_db_session.query(BoardSymbol)
        .filter(BoardSymbol.board_id == board_id)
        .all()
    )
    assert len(board_symbols) == 0
