from unittest.mock import AsyncMock, patch

import pytest
from fastapi.testclient import TestClient
from sqlalchemy.orm import Session

from src.aac_app.models import BoardSymbol, CommunicationBoard, User
from src.api.main import app
from tests.test_utils_auth import create_test_headers

# Setup TestClient
client = TestClient(app)


@pytest.fixture
def mock_ai_response():
    return [
        {"label": "Apple", "symbol_key": "apple", "color": "#FFCDD2"},
        {"label": "Banana", "symbol_key": "banana", "color": "#FFF9C4"},
    ]


def test_create_board_with_ai(
    test_db_session: Session, setup_test_db, admin_token, admin_user, mock_ai_response
):
    """Test creating a board with AI enabled"""

    # Mock the BoardGenerationService.generate_board_items method
    # Since we instantiate BoardGenerationService inside the route, we need to patch it
    with patch("src.api.routers.board_ai.BoardGenerationService") as MockServiceClass:
        # Configure the mock instance
        mock_instance = MockServiceClass.return_value
        mock_instance.generate_board_items = AsyncMock(return_value=mock_ai_response)

        # Mock the provider instantiation as well to avoid actual connections
        with patch("src.api.routers.board_ai.OllamaProvider"):

            response = client.post(
                f"/api/boards/?user_id={admin_user.id}",
                headers={"Authorization": f"Bearer {admin_token}"},
                json={
                    "name": "AI Test Board",
                    "description": "A test board generated by AI",
                    "is_public": False,
                    "ai_enabled": True,
                    "ai_provider": "ollama",
                    "ai_model": "llama3",
                },
            )

            assert response.status_code == 200
            data = response.json()
            assert data["name"] == "AI Test Board"
            assert data["ai_enabled"] is True

            board_id = data["id"]

            # Check if symbols were added to the database
            board = (
                test_db_session.query(CommunicationBoard)
                .filter(CommunicationBoard.id == board_id)
                .first()
            )
            assert board is not None

            # Check symbols
            board_symbols = (
                test_db_session.query(BoardSymbol)
                .filter(BoardSymbol.board_id == board_id)
                .all()
            )
            assert len(board_symbols) == 2

            # Check specific symbol content
            symbol_labels = [bs.custom_text for bs in board_symbols]
            assert "Apple" in symbol_labels
            assert "Banana" in symbol_labels

            # Verify generate_board_items was called
            mock_instance.generate_board_items.assert_called_once()
            args, _ = mock_instance.generate_board_items.call_args
            assert args[0] == "AI Test Board"  # topic/name


def test_unrelated_teacher_cannot_use_ai_suggestions_on_student_board(
    test_db_session: Session, setup_test_db
):
    """AI board mutations require an explicit teacher/student roster link."""
    teacher = User(
        username="unrelated_ai_teacher",
        display_name="Unrelated AI Teacher",
        user_type="teacher",
        password_hash="test-hash",
    )
    student = User(
        username="ai_board_student",
        display_name="AI Board Student",
        user_type="student",
        password_hash="test-hash",
    )
    test_db_session.add_all([teacher, student])
    test_db_session.commit()

    board = CommunicationBoard(
        user_id=student.id,
        name="Student AI Board",
        ai_enabled=True,
        ai_provider="ollama",
        ai_model="test-model",
    )
    test_db_session.add(board)
    test_db_session.commit()

    response = client.post(
        f"/api/boards/{board.id}/ai/suggestions",
        headers=create_test_headers(teacher.id, teacher.username, teacher.user_type),
        json={"item_count": 1},
    )

    assert response.status_code == 403

    apply_response = client.post(
        f"/api/boards/{board.id}/ai/suggestions/apply",
        headers=create_test_headers(teacher.id, teacher.username, teacher.user_type),
        json={"item": {"label": "Unauthorized symbol"}},
    )

    assert apply_response.status_code == 403


def test_create_board_with_ai_lmstudio_provider(
    test_db_session: Session, setup_test_db, admin_token, admin_user, mock_ai_response
):
    """LM Studio is a first-class AI provider for board generation."""
    with patch("src.api.routers.board_ai.BoardGenerationService") as MockServiceClass:
        mock_instance = MockServiceClass.return_value
        mock_instance.generate_board_items = AsyncMock(return_value=mock_ai_response)

        with patch("src.api.routers.board_ai.LMStudioProvider"):
            response = client.post(
                f"/api/boards/?user_id={admin_user.id}",
                headers={"Authorization": f"Bearer {admin_token}"},
                json={
                    "name": "AI LM Studio Board",
                    "description": "Generated via LM Studio",
                    "is_public": False,
                    "ai_enabled": True,
                    "ai_provider": "lmstudio",
                    "ai_model": "local-model",
                },
            )

            assert response.status_code == 200
            data = response.json()
            assert data["ai_enabled"] is True

            board_symbols = (
                test_db_session.query(BoardSymbol)
                .filter(BoardSymbol.board_id == data["id"])
                .all()
            )
            assert len(board_symbols) == 2


def test_create_board_rejects_unknown_ai_provider(
    test_db_session: Session, setup_test_db, admin_token, admin_user
):
    """Only the three configured AI providers are accepted for board generation."""
    response = client.post(
        f"/api/boards/?user_id={admin_user.id}",
        headers={"Authorization": f"Bearer {admin_token}"},
        json={
            "name": "Unknown Provider Board",
            "is_public": False,
            "ai_enabled": True,
            "ai_provider": "gpt4",
            "ai_model": "gpt-4",
        },
    )

    assert response.status_code == 400


def test_resolve_provider_for_board_supports_lmstudio(
    test_db_session: Session, setup_test_db, admin_user
):
    """Board AI suggestions resolve an LM Studio provider for lmstudio boards."""
    from src.aac_app.providers.lmstudio_provider import LMStudioProvider
    from src.api.routers.board_ai import _resolve_provider_for_board

    board = CommunicationBoard(
        user_id=admin_user.id,
        name="LM Studio Suggestions Board",
        ai_enabled=True,
        ai_provider="lmstudio",
        ai_model="local-model",
    )
    test_db_session.add(board)
    test_db_session.commit()

    provider = _resolve_provider_for_board(board, test_db_session)

    assert isinstance(provider, LMStudioProvider)
    assert provider._configured_model == "local-model"


def test_create_board_without_ai(
    test_db_session: Session, setup_test_db, admin_token, admin_user
):
    """Test creating a board without AI enabled"""

    response = client.post(
        f"/api/boards/?user_id={admin_user.id}",
        headers={"Authorization": f"Bearer {admin_token}"},
        json={
            "name": "Manual Board",
            "description": "A manually created board",
            "is_public": False,
            "ai_enabled": False,
        },
    )

    assert response.status_code == 200
    data = response.json()
    board_id = data["id"]

    # Check symbols - should be empty
    board_symbols = (
        test_db_session.query(BoardSymbol)
        .filter(BoardSymbol.board_id == board_id)
        .all()
    )
    assert len(board_symbols) == 0
