"""In-process delivery of persisted notifications to SSE subscribers."""

import asyncio
from collections import deque
from dataclasses import dataclass
from datetime import datetime
from threading import Lock, RLock
from typing import Any

from sqlalchemy import event
from sqlalchemy.orm import Session

SUBSCRIBER_QUEUE_MAXSIZE = 100
_PENDING_NOTIFICATIONS_KEY = "aac_pending_notification_events"


class _SubscriberQueue(asyncio.Queue[dict[str, Any]]):
    """Bounded SSE queue that drops the oldest event when it overflows.

    SSE clients that stop reading must not retain an unbounded number of
    notifications.  We preserve the newest events by dropping the oldest
    pending event and count each drop for observability.  Heartbeats are
    generated by the stream independently, so a slow but alive client is not
    disconnected merely because its queue is full.
    """

    def __init__(self) -> None:
        super().__init__(maxsize=SUBSCRIBER_QUEUE_MAXSIZE)
        self._pending_events: deque[dict[str, Any]] = deque()
        self._pending_lock = Lock()
        self._drain_scheduled = False
        self.dropped_count = 0

    def schedule(self, event: dict[str, Any], loop: asyncio.AbstractEventLoop) -> bool:
        """Queue an event and coalesce delivery callbacks for a busy loop."""
        with self._pending_lock:
            if len(self._pending_events) >= SUBSCRIBER_QUEUE_MAXSIZE:
                self._pending_events.popleft()
                self.dropped_count += 1
            self._pending_events.append(event)
            if self._drain_scheduled:
                return True
            self._drain_scheduled = True

        try:
            loop.call_soon_threadsafe(self._drain)
        except RuntimeError:
            # The stream's loop has already shut down. Its generator cleanup
            # will remove the stale subscriber when possible.
            with self._pending_lock:
                self._drain_scheduled = False
                self._pending_events.clear()
            return False
        return True

    def _drain(self) -> None:
        """Move coalesced events into the asyncio queue on its owning loop."""
        with self._pending_lock:
            pending = tuple(self._pending_events)
            self._pending_events.clear()
            self._drain_scheduled = False

        for event_item in pending:
            if self.full():
                self.get_nowait()
                with self._pending_lock:
                    self.dropped_count += 1
            self.put_nowait(event_item)


@dataclass(frozen=True)
class _Subscriber:
    """An SSE queue and the event loop that owns it."""

    queue: asyncio.Queue[dict[str, Any]]
    loop: asyncio.AbstractEventLoop


_subscribers: dict[int, set[_Subscriber]] = {}
_subscriber_lock = RLock()


def subscribe(user_id: int) -> _SubscriberQueue:
    """Register an SSE queue for a user and return it to the stream."""
    loop = asyncio.get_running_loop()
    queue = _SubscriberQueue()
    with _subscriber_lock:
        _subscribers.setdefault(user_id, set()).add(_Subscriber(queue, loop))
    return queue


def unsubscribe(user_id: int, queue: asyncio.Queue[dict[str, Any]]) -> None:
    """Remove an SSE queue when its stream disconnects."""
    with _subscriber_lock:
        subscribers = _subscribers.get(user_id)
        if not subscribers:
            return

        stale_subscribers = {
            subscriber
            for subscriber in tuple(subscribers)
            if subscriber.queue is queue
        }
        subscribers.difference_update(stale_subscribers)
        if not subscribers:
            _subscribers.pop(user_id, None)


def notification_payload(notification: Any) -> dict[str, Any]:
    """Convert a notification ORM object into the public SSE payload."""
    return {
        "id": notification.id,
        "title": notification.title,
        "message": notification.message,
        "type": notification.notification_type,
        "priority": notification.priority,
        "is_read": notification.is_read,
        "created_at": _isoformat(notification.created_at),
        "read_at": _isoformat(notification.read_at),
    }


def publish_notification(notification: Any) -> None:
    """Publish a persisted notification to all subscribers for its user."""
    _publish_event(notification_payload(notification), notification.user_id)


def stage_notification(session: Session, notification: Any) -> None:
    """Stage a notification event for publication after ``session`` commits."""
    pending = session.info.setdefault(_PENDING_NOTIFICATIONS_KEY, [])
    pending.append((notification_payload(notification), notification.user_id))


@event.listens_for(Session, "after_commit")
def _publish_staged_notifications(session: Session) -> None:
    """Publish staged notifications only after the transaction commits."""
    pending = session.info.pop(_PENDING_NOTIFICATIONS_KEY, ())
    for event_payload, user_id in pending:
        _publish_event(event_payload, user_id)


@event.listens_for(Session, "after_rollback")
def _discard_staged_notifications(session: Session) -> None:
    """Discard events from transactions that did not commit."""
    session.info.pop(_PENDING_NOTIFICATIONS_KEY, None)


def _publish_event(event_payload: dict[str, Any], user_id: int) -> None:
    with _subscriber_lock:
        subscribers = tuple(_subscribers.get(user_id, ()))

    for subscriber in subscribers:
        if not subscriber.queue.schedule(event_payload, subscriber.loop):
            with _subscriber_lock:
                _subscribers.get(user_id, set()).discard(subscriber)


def _isoformat(value: datetime | None) -> str | None:
    return value.isoformat() if value else None
